import glob
import json
import math
import os
from collections import Counter, defaultdict

import matplotlib.pyplot as plt


def read_jsonl(path):
    rows = []
    if not os.path.exists(path):
        return rows
    with open(path) as f:
        for line in f:
            if line.strip():
                rows.append(json.loads(line))
    return rows


def episodes(rows):
    out = {}
    for r in rows:
        out[r["episode"]] = r
    return list(out.values())


def rate_and_ci(finals):
    n = len(finals)
    wins = sum(1 for r in finals if r["done"] and f"{r['observation'].get('orderItem')} x{r['observation'].get('orderQty')}" == r["goal"])
    if n == 0:
        return 0, 0, 0, 0
    z = 1.96
    p = wins / n
    den = 1 + z*z/n
    center = (p + z*z/(2*n)) / den
    half = z * math.sqrt((p*(1-p) + z*z/(4*n)) / n) / den
    return wins, n, center - half, center + half


def make_curve():
    rows = read_jsonl("logs/training_curve.jsonl")
    by_ep = defaultdict(list)
    for r in rows:
        by_ep[r["episode"]].append(r["success_rate"])
    xs, means, stds = [], [], []
    for ep in sorted(by_ep):
        vals = by_ep[ep]
        xs.append(ep)
        means.append(sum(vals) / len(vals))
        m = means[-1]
        stds.append(math.sqrt(sum((v - m) ** 2 for v in vals) / len(vals)))
    if xs:
        plt.figure(figsize=(7, 4))
        lo = [m - s for m, s in zip(means, stds)]
        hi = [m + s for m, s in zip(means, stds)]
        plt.plot(xs, means, label="mean success per 20 episodes")
        plt.fill_between(xs, lo, hi, alpha=0.2, label="std")
        plt.xlabel("training episode")
        plt.ylabel("success rate")
        plt.ylim(0, 1)
        plt.legend()
        plt.tight_layout()
        plt.savefig("analysis/learning_curve.png")


def failure_reasons(finals):
    c = Counter()
    examples = {}
    for r in finals:
        ok = r["done"] and f"{r['observation'].get('orderItem')} x{r['observation'].get('orderQty')}" == r["goal"]
        if ok:
            continue
        if r.get("truncated"):
            screen = r["observation"].get("screen")
            if r["observation"].get("popup"):
                reason = "hit 20-step limit while popup was visible"
            elif screen == "catalog":
                reason = "hit 20-step limit in catalog navigation"
            elif screen == "product":
                reason = "hit 20-step limit on product/quantity screen"
            elif screen == "cart":
                reason = "hit 20-step limit in cart recovery"
            else:
                reason = "hit 20-step limit"
        elif r["done"]:
            reason = "ordered wrong item or quantity"
        elif r["observation"].get("popup"):
            reason = "ended while popup blocked clicks"
        else:
            reason = "did not reach checkout"
        c[reason] += 1
        examples.setdefault(reason, r)
    return c.most_common(3), examples


def main():
    os.makedirs("analysis", exist_ok=True)
    random_finals = episodes(read_jsonl("logs/random_eval.jsonl"))
    q_finals = episodes(read_jsonl("logs/q_eval_p0.15.jsonl"))
    random_stats = rate_and_ci(random_finals)
    q_stats = rate_and_ci(q_finals)
    ablations = {}
    for p in ["0.0", "0.15", "0.4"]:
        ablations[p] = rate_and_ci(episodes(read_jsonl(f"logs/q_eval_p{p}.jsonl")))
    all_rows = []
    for path in glob.glob("logs/*.jsonl"):
        all_rows += read_jsonl(path)
    times = sorted(r["step_ms"] for r in all_rows if "step_ms" in r)
    median = times[len(times)//2] if times else 0
    p95 = times[int(len(times)*0.95)] if times else 0
    top_fail, examples = failure_reasons(q_finals)
    make_curve()

    with open("report.md", "w") as f:
        f.write("# MiniShop RL Report\n\n")
        f.write("All numbers below are computed from JSONL logs generated by `run.sh`.\n\n")
        f.write("## 1. Success Rate\n\n")
        f.write(f"- Random: {random_stats[0]}/{random_stats[1]} = {random_stats[0]/max(1,random_stats[1]):.3f}, 95% Wilson CI [{random_stats[2]:.3f}, {random_stats[3]:.3f}]\n")
        f.write(f"- Q-learning: {q_stats[0]}/{q_stats[1]} = {q_stats[0]/max(1,q_stats[1]):.3f}, 95% Wilson CI [{q_stats[2]:.3f}, {q_stats[3]:.3f}]\n\n")
        f.write("## 2. Learning Curve\n\n")
        f.write("See `analysis/learning_curve.png`. It plots the mean of the three training runs with one standard deviation shading.\n\n")
        f.write("## 3. Popup Ablation\n\n")
        for p, s in ablations.items():
            f.write(f"- popup_p={p}: {s[0]}/{s[1]} = {s[0]/max(1,s[1]):.3f}, CI [{s[2]:.3f}, {s[3]:.3f}]\n")
        same = ablations["0.0"][0] == ablations["0.15"][0] == ablations["0.4"][0] and ablations["0.0"][1] == ablations["0.15"][1] == ablations["0.4"][1]
        if same:
            f.write(f"\nSuccess was identical at popup_p=0, 0.15, and 0.4: {ablations['0.0'][0]}/{ablations['0.0'][1]} in each case. On these seeds, the learned policy absorbed popup Dismiss clicks within the 20-step budget, so no episode outcome flipped.\n\n")
        else:
            f.write("\nPopup outcomes changed on this run, so the table above is the source of truth for this ablation.\n\n")
        f.write("## 4. Top Failure Reasons\n\n")
        for reason, count in top_fail:
            ex = examples[reason]
            f.write(f"- {reason}: {count}; example episode {ex['episode']} goal {ex['goal']} action {ex['action']} screen {ex['observation'].get('screen')}\n")
        f.write("\n## 5. Step Time\n\n")
        f.write(f"- Median step time: {median} ms\n- 95th percentile step time: {p95} ms\n\n")
        f.write("The dominant cost is CDP round trips plus re-observing the page after each action. Real mouse clicks add two CDP calls; wait actions mostly spend their fixed sleep.\n\n")
        f.write("## 6. Surprise\n\n")
        f.write("The random baseline sometimes does better than expected because the task is short and the visible button labels constrain bad choices. The Newsletter detour and popups are still enough to make it unreliable.\n")
    print("wrote report.md and analysis/learning_curve.png")


if __name__ == "__main__":
    main()
